### ISSUE TITLE
Building Test Application Failed

### ISSUE THREAD

**Issue by khmarbaise** [flowing/flowing-trip-booking-saga#3]
After changing the version for `camunda-util-demo-support` from 0.4.0 to  0.4.1 instead
```xml
	<dependency>
 			<groupId>com.camunda.consulting.util</groupId>
 			<artifactId>camunda-util-demo-support</artifactId>
-			<version>0.4.0</version>
+			<version>0.4.1</version>
```
and commented out `src/main/java/io/flowing/trip/saga/camunda/simple/TripBookingSaga.java` to get building correctly with spring boot and tried to start the app and got the following:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 
'tripBookingSaga': Unsatisfied dependency expressed through field 'camunda'; nested exception is
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name
 'processEngineFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NoClassDefFoundError: 
org/camunda/bpm/engine/impl/bpmn/parser/FoxFailedJobParseListener
```
It looks like this is a class which is contained in an older version of Camunda (Taken a look here: https://github.com/joansmith/camunda-bpm-platform) and it exists there...but does not in Camunda CE 7.8.0....Or I miss an other dependency?

Furthermore I have added the following line to the pom file to get rid of WARNINGs:
```xml
+  <properties>
+    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
```

**Comment by iamzgy48** [comment]
I got same error when try to run this demo, where is org/camunda/bpm/engine/impl/bpmn/parser/FoxFailedJobParseListener invoked?

**Comment by berndruecker** [comment]
Hey guys.
Thanks for reporting this! And sorry for the delay, I just came back to work this week. I updated everything to the latest version and removed the helper - as this is no longer necessary anyway.

https://github.com/flowing/flowing-trip-booking-saga/commit/0c7ce1203b6f257ee6f766e91338a71842a61bea

Works fine for me now - could you double check?

Thanks
Bernd
